# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: c8a894d133a3e975913f95dffee2a0ef042c99e155fc2e3f47913437f69a0b2e9004f4a5bf30578c7467e4dc85bb1a4bc8b9f3fbdabf020b9ef82c22b0461fa4

test:
  domain_name: example.com 
  secret_key_base: 563e9e4b076e4beafc231e930225ee7adae118f09fd3f9aa8239b15e32ac85e1f26b7447f09a12eaf727893e0040687c2d9c42eb71c35ea4901d1ea87930089d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
